name: CI Extension

on:
  push:
    branches: [main]
    paths:
      - "apps/extension/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci-extension.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/extension/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci-extension.yml"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm format:check

      - run: pnpm check-types

      - run: pnpm -F @cptr/extension exec playwright install chromium

      - run: pnpm -F @cptr/extension test
